spring:
  datasource:
    url: jdbc:h2:mem:walletdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    open-in-view: false


springdoc:
  swagger-ui:
    path: /docs